# -*- coding: utf-8 -*-
"""validate1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cPiYeMQGa70HLVzmXpecla2pLTXBneF9
"""

import re
def val_AccountNumber(AccNo):
  pattern=r'^[A-Z]{3}\d{3}$'
  if re.match(pattern,AccNo):
    return True
  else:
    return False


def val_AccName(name):
  ans=False
  if(name.istitle()):
    if(len(name.split())==3):
      ans=True
  return ans


def val_Gen(gen):
  if gen=='male' or gen=='female':
    return True
  else:
    return False


from datetime import datetime
import re
def val_Dob(dob):
  format = '%d-%m-%Y'
  try:
    val=bool(datetime.strptime(dob,format))
  except ValueError:
    val=False
  return val


def val_City(city):
  if city.isalpha():
    return True
  else:
    return False


def val_AccType(acctype):
  if acctype=='savings' or acctype=='current' or acctype=='joint':
    return True
  else:
    return False


import re
def val_PanNumber(panNo):
  pattern=r"^[A-Z]{5}\d{4}[A-Z]{1}$"
  if re.match(pattern,panNo):
    return True
  else:
    return False


def val_AdNumber(adnum):
  val=False
  if adnum.isdigit():
    if len(adnum)==12:
      val=True
  return val

